### ISSUE TITLE
Maxcube2 crashing nodered all of a sudden 

### ISSUE THREAD

**Issue by chrisghz** [normen/maxcube2#13]
Hi 
Has anyone else notice that the maxcube2 nodes are suddenly crippling nodered installations? I finally managed to get my rather extensive flows back up and running after finding maxcube, again to be the root cause. Below is my debug output, if anyone could shed any light on what on earth is going on, I'd be forever in their debt.

4 Jun 12:50:49 - [info] Starting flows
4 Jun 12:50:49 - [info] Started flows
4 Jun 12:50:49 - [red] Uncaught Exception:
4 Jun 12:50:49 - TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Bu        ffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at new Buffer (buffer.js:286:17)
    at Object.parseCommandMetadata (/home/pi/.node-red/node_modules/maxcube/maxcube-commandparser.js:65:24)
    at Object.parse (/home/pi/.node-red/node_modules/maxcube/maxcube-commandparser.js:19:35)
    at MaxCubeLowLevel.<anonymous> (/home/pi/.node-red/node_modules/maxcube/maxcube.js:41:46)
    at MaxCubeLowLevel.emit (events.js:314:20)
    at /home/pi/.node-red/node_modules/maxcube/maxcube-lowlevel.js:39:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/maxcube/maxcube-lowlevel.js:35:16)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 11.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
4 Jun 12:51:11 - [info]
Welcome to Node-RED
===================
4 Jun 12:51:11 - [info] Node-RED version: v1.2.6
4 Jun 12:51:11 - [info] Node.js  version: v12.20.1
4 Jun 12:51:11 - [info] Linux 5.10.11-v7l+ arm LE
4 Jun 12:51:11 - [info] Loading palette nodes
^Z
[1]+  Stopped                 node-red-start

**Comment by normen** [comment]
Looks like thats the original maxcube library, not maxcube2

**Comment by chrisghz** [comment]
Thanks, however I just created a new container, fresh everything, installed maxcube2 and get this.....

4 Oct 20:46:33 - [info] [maxcube-server:e7a79aee42a6dffc] "Problem while parsing the command 'M': TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at Function.from (buffer.js:330:9)\n    at Object.parseCommandMetadata (/data/node_modules/maxcube2/maxcube-commandparser.js:66:31)\n    at Object.parse (/data/node_modules/maxcube2/maxcube-commandparser.js:20:35)\n    at MaxCubeLowLevel.<anonymous> (/data/node_modules/maxcube2/maxcube.js:63:48)\n    at MaxCubeLowLevel.emit (events.js:400:28)\n    at /data/node_modules/maxcube2/maxcube-lowlevel.js:46:14\n    at Array.forEach (<anonymous>)\n    at Socket.<anonymous> (/data/node_modules/maxcube2/maxcube-lowlevel.js:42:16)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"

Any Ideas? 

Winters on it's way and I need my temp sensors .... :-(

**Comment by normen** [comment]
What is maxcube-server? In what context do you use this library? I don't get any errors when using it in homebridge-platform-maxcube.

**Comment by chrisghz** [comment]
I'm using it on node-red 2.0.6. Installed freshly from the pallet manager.

**Comment by normen** [comment]
...and some plugin I suppose...?

**Comment by normen** [comment]
Is this what you use? https://www.npmjs.com/package/node-red-contrib-maxcube2

**Comment by chrisghz** [comment]
I installed from the nodered pallet manager which looks to pull the same one i
<img width="700" alt="Screenshot 2021-10-04 at 23 43 40" src="https://user-images.githubusercontent.com/7511361/135934525-5f56ef96-cbd5-4e87-bdec-861078931cbb.png">
n?

**Comment by normen** [comment]
I can't really say as I can't test when and how this happens, this is just the library that the plugin above (which is not by me) is using. Maybe check the issue tracker for that plugin to see if your issue came up already: [https://github.com/maxill1/node-red-contrib-maxcube2/issues](https://github.com/maxill1/node-red-contrib-maxcube2/issues?q=is%3Aissue+is%3Aclosed+is%3Aopened)

**Comment by chrisghz** [comment]
Hi @normen , just another one for you, I've installed the plugin in my homebridge instance and seem to be getting the same error. I've just restored my cube to factory default in case this is causing the issues, but no change. I'm going to try and use the Max mac app to re-add some devices and see if it still works. Just thought it was odd I'm getting a similar error in nodered and homebridge. 

[10/5/2021, 4:54:03 PM] [MaxCube Platform] Max! Cube connection error!
[10/5/2021, 4:54:03 PM] [MaxCube Platform] Problem while parsing the command 'M': TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Object.parseCommandMetadata (/homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-commandparser.js:66:31)
    at Object.parse (/homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-commandparser.js:20:35)
    at MaxCubeLowLevel.<anonymous> (/homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube.js:63:48)
    at MaxCubeLowLevel.emit (events.js:400:28)
    at /homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:46:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:42:16)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by chrisghz** [comment]
UPDATE: A total factory reset seems to have done the job. I can only think that the cube had a total wobble over the summer and I missed it as the heating controls were all but off.

**Comment by normen** [comment]
Yes, the Cube does seem to have a few bugs. I also get issues when the thermostats are run in "Manual" mode for too long, after a few weeks the cube can't reach them anymore. Never saw this error message appear though but as said - the plugin you use might use this library in a different way.
